DROP SCHEMA IF EXISTS rentauto;
CREATE SCHEMA rentauto;

USE rentauto;

CREATE TABLE `rentauto`.`Usuarios` (
  `NOMBRE` VARCHAR(255)  NOT NULL,
  `APELLIDO` VARCHAR(255)  NOT NULL,
  `EMAIL` VARCHAR(255)  NOT NULL,
  `FNAC` DATE  NOT NULL,
  `USERNAME` VARCHAR(255)  NOT NULL,
  `VALCODE` VARCHAR(255)  NOT NULL,
  `PASSWORD` VARCHAR(255)  NOT NULL,
  PRIMARY KEY (`USERNAME`),
)

CREATE TABLE `Auto`(
	`ID` INT,
	`MARCA` VARCHAR(255) NOT NULL,
	`MODELO` VARCHAR(255) NOT NULL,
	`AÑO` INT NOT NULL,
	`PATENTE` VARCHAR (255) NOT NULL,
	`COSTOBASE` DOUBLE NOT NULL,
	PRIMARY KEY (`ID`)
ENGINE = InnoDB;
